### ISSUE TITLE
Abaqus使用方法の習得

### ISSUE THREAD

**Issue by KotaTsuboi** [shiroi36/wcs-study#3]
### Abaqus例題実行メモ
[Abaqusマニュアル](https://help.3ds.com/2021/English/DSSIMULIA_Established/SIMACAEGSARefMap/simagsa-c-ov.htm?contextscope=all&redirect_lang=English)のAbaqus Basics > Example: creating a model of an overhead hoistを学んだメモ

#### パートの作成
モデルツリーの「パート」をダブルクリックして「パートの作成」を開く。
「近似サイズ」はスケッチ画面のサイズやグリッド間隔に用いられ、仕上がり寸法程度の値を入力する。
Sketcherが起動するので幾何拘束や寸法拘束を利用して作成したいパートを作成する。

#### 材料の作成
モデルツリーの「材料特性」をダブルクリックして「材料特性の編集」を開く。
下のメニューから例えば「機械的」→「弾性」→「弾性」のように選択する。
「データ」欄でヤング率とポアソン比を入力する。

#### 要素特性の作成
モデルツリーの「要素特性」をダブルクリックして「要素特性の作成」を開く。
例えば「はり」と「トラス」を選択する。
「要素特性の編集」で材料特性を選択し、断面積を入力する。ここでは`pi*0.025**2/4.0`のような計算式が入力できる。

#### 要素特性割り当て
モデルツリーで作成したパートを展開し、「要素特性割り当て」をダブルクリックする。
ビューポートで割り当てる要素を選択する。
「要素特性割り当ての編集」で割り当てる要素特性を選択する。

#### アセンブリの定義
モデルツリーで「アセンブリ」を展開し、「インスタンス」をダブルクリックして「インスタンスの作成」を開く。
例えば「パート」を選択し、含むパートを選択する。
アセンブリはモデルに1つのみで、パートのインスタンスをグローバル座標系に配置することで定義される。
インスタンスはインディペンデントとディペンデントの2種類があり、メッシュのされ方が異なる。

#### ステップの作成
モデルツリーの「ステップ」をダブルクリックして「ステップの作成」を開く。
「プロシージャタイプ」の「線形摂動」は線形解析のみに利用可能。
例えば「Static, Linear perturbation」を選択する。

#### 出力項目の管理
モデルツリーで「ステップ」の各ステップを展開し、「フィールド出力要求」を右クリックして「管理」をクリックする。
フィールド出力要求マネージャが開くので出力する変数などを変更できる。
出力ファイルは.odb, .dat, .res, .filの4種類ある。
（マニュアルあまり読めてないので追記する）

#### 境界条件の設定
モデルツリーで「ステップ」の各ステップを展開し、「境界条件」をダブルクリックして「境界条件の作成」を開く。
例えば、最初のステップを選択し、「機械的」と「変位/回転」を選択する。
境界条件を設定する節点を選択し、「境界条件の編集」で拘束する項目をオンにする。
「境界条件」を右クリックして「管理」をクリックすると継承関係を設定できる。

#### 荷重の設定
「荷重」をダブルクリックして「荷重の作成」を開く。
例えば、2番目のステップで「機械的」と「集中力」を選択する。
荷重を設定する節点を選択し、「荷重の編集」で例えばCF2を-10000にする。

#### 要素タイプの割り当て
モデルツリーで各パートを展開し、「メッシュ」をダブルクリックすると「メッシュ」モジュールに切り替わる。
メインメニューで「メッシュ」→「要素タイプ」を選択する。
このとき画面右下の「集合」をクリックすると定義した集合を用いて割り当てができる。
「要素タイプ」で例えば「Standard」、「線形」、「トラス」を選択する。

#### メッシュの作成
メインメニューで「シード」→「パート」をクリックし、「全体シード」を開く。
近似全体サイズを設定する。
メインメニューで「メッシュ」→「パート」をクリックし、メッシュを作成する。

#### ジョブの作成
ジョブはモデルツリーから「ジョブ」をダブルクリックして作成する。

#### データチェックとジョブの投入
モデルツリーの「解析」→「ジョブ」にジョブの一覧があるので、右クリック→「データチェック」でデータのチェックをする。
ジョブ名に「チェック完了」が付いたら右クリック→「続ける」でジョブを投入する。
データチェックとジョブの投入を同時にするには右クリック→「ジョブの投入」を選択する。
#### 結果表示
ジョブ名を右クリック→「結果」あるいはモジュールで「結果表示」を選択し「ファイル」→「開く」からジョブで出力された.odbファイルを選択すると結果を表示する。

#### 材料特性の確認
モデルツリーの「出力データベース」に現在のセッションの出力データベース一覧が表示されている。
そのうち1つを展開してその中の「材料特性」を展開すると使用している材料一覧が表示される。
そのうち1つを選択するとビューポート上で対応する部材がハイライト表示される。

#### 節点番号と部材番号の表示
![image](https://github.com/KotaTsuboi/wcs-study/assets/41675201/c1aa5144-9934-4eae-b2d6-8db972f38535)をクリックすると共通プロットオプションが開く。
ラベルタブから「要素ラベルの表示」および「節点ラベルの表示」をオンにすると節点番号と部材番号を表示する。

#### 変形図の表示
![image](https://github.com/KotaTsuboi/wcs-study/assets/41675201/306b6aac-4b00-4b18-af96-2e5853acbdb5)をクリックして変形図を表示する。
変形倍率を変更するには前節のやり方で共通プロットオプションを開いて「基本」タブの「変形倍率」欄で「均一」を選択し、値を入力する。
原形図と重ねて表示するには![image](https://github.com/KotaTsuboi/wcs-study/assets/41675201/fe553fc2-a345-46a2-ba01-a2f8278b79e8)をクリックして複数プロットを許可し、![image](https://github.com/KotaTsuboi/wcs-study/assets/41675201/fac283aa-3f93-44c0-b40c-153e01daac02)をクリックする。
![image](https://github.com/KotaTsuboi/wcs-study/assets/41675201/cbbca488-22b4-43d7-8765-093b0722baee)をクリックすると重ね合わせプロットオプションを開く。
「色とスタイル」タブの「エッジ属性」欄で点線を選択すると原形図を点線表示に変更できる。

#### 境界条件の表示
「ビュー」→「ODB表示オプション」をクリックする。
「エンティティの表示」タブで「境界条件の表示」をオンにすると境界条件がビューポートに表示される。

#### レポートファイル（.rpt）への結果の出力
「レポート」→「フィールド出力」をクリックすると「フィールド出力のレポート」を開く。
「変数」タブで出力値の位置と出力値を選択し、「設定」タブの「ファイル」欄で入力したファイル名に出力する。
複数回出力すると前回内容を上書きせずに追記する。

#### 陽解法への切り替え
モデルツリーでステップを右クリックして「置換」を選択する。
プロシージャタイプを「一般」とし、「Dynamic, Explicit」を選択する。
「ステップの編集」の「基本」タブで例えば時間幅を0.01に設定する。
「履歴出力要求」に変位を追加する。
材料特性をダブルクリック「一般」→「密度」をクリックして密度を例えば7800と入力する。
パートのメッシュをダブルクリックしてメッシュモジュールに切り替え、メインメニューで「メッシュ」→「要素タイプ」をクリックして要素を選択後、「要素ライブラリ」をExplicitに変更する。
ジョブを新たに作成し、「explicit」を選択する。

#### X-Yプロットの出力
「出力データベース」の各odbで「履歴出力」の中に前節の「履歴出力要求」で設定した項目が出力されている。

#### 例題ファイルの取得
Abaqus例題ファイルは`abaqus fetch`コマンドでダウンロードできる
今回のPythonスクリプト`gsi_frame_caemodel.py`をダウンロードするには下記を実行する。
```
abaqus fetch job=gsi_frame_caemodel.py
```
#### Pythonスクリプトの実行
「ファイル」→「スクリプトの実行」

#### 2024年2月26日メモ
> RF：反力 RM：反力モーメント U：変位 UR：回転変位
> これらの値を結果から得られれば良い
> RF1,2,3はX,Y,Z方向に対応する
> データベースを開いた後、画面上の「基本」の右のドロップダウンリストからRF,U,URを選択すればその結果が見られる
> 「共通プロットオプション」から変形倍率を設定
> 「結果表示」モジュールの「XYデータマネージャ」を開く
> 作成→ODBフィールド出力→位置は節点→出力する変数を選択（RF1とU1等）→ビューポートからピック→参照点は荷重を与えている点→保存→XとYのデータとして出力される→レポートのXYで「適用」をする→rptファイルで出力される
> プラグイン→abaqus→はじめに→exampleが見れる

- [x] 「はじめに」からAbaqusの使い方を学ぶ 4h
    - マニュアルを参照しながら
- [x] 以下を伊山先生に聞くため、Slackでウェブ会議を調整する
    - 荷重変形関係をデータベースに出力する方法
    - プログラムをzip等で共有してもらう
    - 使用方法を知るため、サンプルプログラムがあれば教えてもらう

### 2024年3月6日伊山先生打ち合わせメモ
1. .inpファイルに出力する変数を追記する
`OUTPUT` コマンドの下に例えば下記を追記する。
この例ではU（変位）、RF（反力）、SF（断面力）が出力される。
```
*NODE FILE
U,RF
*EL FILE
SF
```
2. Abaqusをコマンドから実行
```
abaqus job=name_of_inp_file interactive
```
3. .filが出力されるのでこれを[伊山先生のjavaプログラム](https://1drv.ms/u/s!AvSbCvMv70RqiZcUqF280-eybZ1LyA?e=kFL0Va)でH2に変換する
```
java -cp junlib23-1.0-SNAPSHOT-jar-with-dependencies.jar jun.abaqus.db.FilToH2v12 name_of_fil_file.fil
```
4. .mv.dbファイルが出力されるのでこれでJFreeChartなどでグラフを描く

**Comment by shiroi36** [comment]
[中幅h-434x299x10x15.zip](https://github.com/KotaTsuboi/wcs-study/files/14643718/h-434x299x10x15.zip)

**Comment by shiroi36** [comment]
[c01.zip](https://github.com/KotaTsuboi/wcs-study/files/14643724/c01.zip)

**Comment by KotaTsuboi** [comment]
#### 2024年3月19日メモ
1. ファイル→インポート→スケッチ
2. dxfをインポート
3. パートの作成から「ソリッド・押し出し」
4. スケッチャーオプションからグリッド間隔を調整
5. ベース押し出しの編集
6. 奥行の選択
7. パートごとにメッシュを定義する
8. セルのパーテーション切断面の定義
9. フランジ・R・ウェブ・R・フランジに5分割
10. データム平面を定義　3ポイントで
11. フランジ平面と切断平面を定義
12. 切り取り押し出しの編集で長孔を切り抜く
13. フランジ平面を選択し、長孔のdxfを選択し、貫通を選ぶと孔の形で切り取られる
14. ウェブのボルト孔も同様にして切り取る
15. フェイスのパーテーションスケッチでウェブボルト
16. ボルト孔周りのメッシュを切り分けるためにセルのパーテーションで切る
17. 長孔まわりも同様
18. モジュールをメッシュにするとメッシュが切れるかどうかが確認できる
19. メッシュコントロールで立方体で無い箇所を4面体のフリーとする
20. パートのシードでメッシュサイズを設定
21. 部分的にメッシュサイズを変更する場合はエッジのシードで設定する
